apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume
  labels:
    app: nginx-app
spec:
  containers:
  - image: nginx:latest
    name: nginx-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
  volumes:
  - name: cache-volume
    persistentVolumeClaim:
      claimName: pv-claim


---
kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 8000
      name: nginx
  clusterIP: None