apiVersion: batch/v1
kind: Job
metadata:
  name: multitask-job
spec:
  completions: 5
  parallelism: 3
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: job-container
        image: alpine
        command: ["sh", "-c"]
        args:
        - |
          sleep 3
      restartPolicy: Never