apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-partition
spec:
  serviceName: statefulset-partition
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 3
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.16
        ports:
        - containerPort: 8000
          name: web
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 8000
      name: statfulset-partition
  clusterIP: None


# partionで指定した数以下はアップデートしない。(今回は3なのでpod0～2までは変更されない)