apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-ondelete
spec:
  selector:
    matchLabels:
      app: fluented-app
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: fluented-app
    spec:
      containers:
      - name: fluented-container
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        ports:
        - containerPort: 8000
          name: flunted
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
---
kind: Service
apiVersion: v1
metadata:
  name: fluented-svc
spec:
  selector:
    app: fluented-app
  ports:
    - protocol: TCP
      port: 8000
      name: ds-ondelete
  clusterIP: None